#!/bin/zsh
export PATH="$HOME/.local/go/bin:$HOME/.local/bin:/usr/local/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$HOME/.local/share/gem/ruby/2.7.0/bin:$PATH"
export PATH="$HOME/.local/node_modules/bin:$PATH"
export PATH="$HOME/scripts:$PATH"
export PATH="$HOME/.local/share/bob/nvim-bin:$PATH"
export npm_config_prefix="$HOME/.local/node_modules"
export ZDOTDIR="$HOME/.config/zsh"

export RANGER_LOAD_DEFAULT_RC=false
export IPYTHONDIR="~/.config/ipython"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export GOPATH=$HOME/.local/go
export STARSHIP_CONFIG=$HOME/.config/starship/config.toml
export LUADIR=$HOME/.local/luarocks/
export PREFIX=$HOME/.local/luarocks/lua
export LIBDIR=$HOME/.local/luarocks/lib
export BINDIR=$HOME/.local/luarocks/bin
export CONFDIR=$HOME/.local/luarocks/conf

#personal variables
export ZRC="$ZDOTDIR/.zshrc"
export VIMRC="$HOME/.config/nvim/init.lua"

#start the gnome keyring so that I don't always give my password for the wifi
if [ -n "$DESKTOP_SESSION" ];then
	eval $(gnome-keyring-daemon --start)
	export SSH_AUTH_SOCK
fi
. "$HOME/.cargo/env"
