# Inserts a blank line between shell prompts
add_newline = false

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[ᛰ](bold green)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_visual_symbol = "[](bold yellow)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = " "
