# Inserts a blank line between shell prompts
add_newline = false

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[ᛰ](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = " "
